openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.ListDataQualityResults API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.ListDataQualityResults API'
paths:
  /#X-Amz-Target=AWSGlue.ListDataQualityResults:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListDataQualityResults
      description: Returns all data quality execution results for your account.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListDataQualityResultsResponse'
              examples:
                ListDataQualityResults200Example:
                  summary: Default ListDataQualityResults 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                ListDataQualityResults480Example:
                  summary: Default ListDataQualityResults 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                ListDataQualityResults481Example:
                  summary: Default ListDataQualityResults 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                ListDataQualityResults482Example:
                  summary: Default ListDataQualityResults 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListDataQualityResultsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.ListDataQualityResults
      summary: Amazon Glue List Data Quality Results
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.ListDataQualityResults API'
components:
  schemas:
    DescriptionString:
      type: string
      minLength: 0
      maxLength: 2048
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    ListDataQualityResultsRequest:
      type: object
      title: ListDataQualityResultsRequest
      properties:
        Filter:
          allOf:
          - $ref: '#/components/schemas/DataQualityResultFilterCriteria'
          - description: The filter criteria.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: A paginated token to offset the results.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: The maximum number of results to return.
    HashString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    OperationTimeoutException: {}
    InvalidInputException: {}
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    DataSource:
      type: object
      required:
      - GlueTable
      properties:
        GlueTable:
          allOf:
          - $ref: '#/components/schemas/GlueTable'
          - description: An Glue table.
      description: A data source (an Glue table) for which you want data quality results.
    InternalServiceException: {}
    DataQualityResultDescriptionList:
      type: array
      items:
        $ref: '#/components/schemas/DataQualityResultDescription'
    GlueTableAdditionalOptions:
      type: object
      minProperties: 1
      maxProperties: 10
      additionalProperties:
        $ref: '#/components/schemas/DescriptionString'
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    GlueTable:
      type: object
      required:
      - DatabaseName
      - TableName
      properties:
        DatabaseName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: A database name in the Glue Data Catalog.
        TableName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: A table name in the Glue Data Catalog.
        CatalogId:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: A unique identifier for the Glue Data Catalog.
        ConnectionName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the connection to the Glue Data Catalog.
        AdditionalOptions:
          allOf:
          - $ref: '#/components/schemas/GlueTableAdditionalOptions'
          - description: '<p>Additional options for the table. Currently there are two keys supported:</p> <ul> <li> <p> <code>pushDownPredicate</code>: to filter on partitions without having to list and read all the files in your dataset.</p> </li> <li> <p> <code>catalogPartitionPredicate</code>: to use server-side partition pruning using partition indexes in the Glue Data Catalog.</p> </li> </ul>'
      description: The database and table in the Glue Data Catalog that is used for input or output data.
    DataQualityResultFilterCriteria:
      type: object
      properties:
        DataSource:
          allOf:
          - $ref: '#/components/schemas/DataSource'
          - description: Filter results by the specified data source. For example, retrieving all results for an Glue table.
        JobName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: Filter results by the specified job name.
        JobRunId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: Filter results by the specified job run ID.
        StartedAfter:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Filter results by runs that started after this time.
        StartedBefore:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Filter results by runs that started before this time.
      description: Criteria used to return data quality results.
    PaginationToken:
      type: string
    Timestamp:
      type: string
      format: date-time
    DataQualityResultDescription:
      type: object
      properties:
        ResultId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The unique result ID for this data quality result.
        DataSource:
          allOf:
          - $ref: '#/components/schemas/DataSource'
          - description: The table name associated with the data quality result.
        JobName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The job name associated with the data quality result.
        JobRunId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The job run ID associated with the data quality result.
        StartedOn:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time that the run started for this data quality result.
      description: Describes a data quality result.
    ListDataQualityResultsResponse:
      type: object
      required:
      - Results
      properties:
        Results:
          allOf:
          - $ref: '#/components/schemas/DataQualityResultDescriptionList'
          - description: A list of <code>DataQualityResultDescription</code> objects.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: A pagination token, if more results are available.
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
