openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetUserDefinedFunctions API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.GetUserDefinedFunctions API'
paths:
  /#X-Amz-Target=AWSGlue.GetUserDefinedFunctions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetUserDefinedFunctions
      description: Retrieves multiple function definitions from the Data Catalog.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserDefinedFunctionsResponse'
              examples:
                GetUserDefinedFunctions200Example:
                  summary: Default GetUserDefinedFunctions 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                GetUserDefinedFunctions480Example:
                  summary: Default GetUserDefinedFunctions 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                GetUserDefinedFunctions481Example:
                  summary: Default GetUserDefinedFunctions 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                GetUserDefinedFunctions482Example:
                  summary: Default GetUserDefinedFunctions 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                GetUserDefinedFunctions483Example:
                  summary: Default GetUserDefinedFunctions 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '484':
          description: GlueEncryptionException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlueEncryptionException'
              examples:
                GetUserDefinedFunctions484Example:
                  summary: Default GetUserDefinedFunctions 484 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetUserDefinedFunctionsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetUserDefinedFunctions
      summary: Amazon Glue Get User Defined Functions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.GetUserDefinedFunctions API'
components:
  schemas:
    ResourceUriList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceUri'
      minItems: 0
      maxItems: 1000
    ResourceUri:
      type: object
      properties:
        ResourceType:
          allOf:
          - $ref: '#/components/schemas/ResourceType'
          - description: The type of the resource.
        Uri:
          allOf:
          - $ref: '#/components/schemas/URI'
          - description: The URI for accessing the resource.
      description: The URIs for function resources.
    GetUserDefinedFunctionsRequest:
      type: object
      required:
      - Pattern
      title: GetUserDefinedFunctionsRequest
      properties:
        CatalogId:
          allOf:
          - $ref: '#/components/schemas/CatalogIdString'
          - description: The ID of the Data Catalog where the functions to be retrieved are located. If none is provided, the Amazon Web Services account ID is used by default.
        DatabaseName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the catalog database where the functions are located. If none is provided, functions from all the databases across the catalog will be returned.
        Pattern:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: An optional function-name pattern string that filters the function definitions returned.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/Token'
          - description: A continuation token, if this is a continuation call.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/CatalogGetterPageSize'
          - description: The maximum number of functions to return in one response.
    UserDefinedFunction:
      type: object
      properties:
        FunctionName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the function.
        DatabaseName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the catalog database that contains the function.
        ClassName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The Java class that contains the function code.
        OwnerName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The owner of the function.
        OwnerType:
          allOf:
          - $ref: '#/components/schemas/PrincipalType'
          - description: The owner type.
        CreateTime:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time at which the function was created.
        ResourceUris:
          allOf:
          - $ref: '#/components/schemas/ResourceUriList'
          - description: The resource URIs for the function.
        CatalogId:
          allOf:
          - $ref: '#/components/schemas/CatalogIdString'
          - description: The ID of the Data Catalog in which the function resides.
      description: Represents the equivalent of a Hive user-defined function (<code>UDF</code>) definition.
    CatalogIdString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    CatalogGetterPageSize:
      type: integer
      minimum: 1
      maximum: 100
    ResourceType:
      type: string
      enum:
      - JAR
      - FILE
      - ARCHIVE
    OperationTimeoutException: {}
    InvalidInputException: {}
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    Token:
      type: string
    PrincipalType:
      type: string
      enum:
      - USER
      - ROLE
      - GROUP
    InternalServiceException: {}
    UserDefinedFunctionList:
      type: array
      items:
        $ref: '#/components/schemas/UserDefinedFunction'
    URI:
      type: string
      minLength: 1
      maxLength: 1024
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    GetUserDefinedFunctionsResponse:
      type: object
      properties:
        UserDefinedFunctions:
          allOf:
          - $ref: '#/components/schemas/UserDefinedFunctionList'
          - description: A list of requested function definitions.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/Token'
          - description: A continuation token, if the list of functions returned does not include the last requested function.
    Timestamp:
      type: string
      format: date-time
    GlueEncryptionException: {}
    EntityNotFoundException: {}
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
