openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetPartitionIndexes API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.GetPartitionIndexes API'
paths:
  /#X-Amz-Target=AWSGlue.GetPartitionIndexes:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetPartitionIndexes
      description: Retrieves the partition indexes associated with a table.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetPartitionIndexesResponse'
              examples:
                GetPartitionIndexes200Example:
                  summary: Default GetPartitionIndexes 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                GetPartitionIndexes480Example:
                  summary: Default GetPartitionIndexes 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                GetPartitionIndexes481Example:
                  summary: Default GetPartitionIndexes 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                GetPartitionIndexes482Example:
                  summary: Default GetPartitionIndexes 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                GetPartitionIndexes483Example:
                  summary: Default GetPartitionIndexes 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '484':
          description: ConflictException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictException'
              examples:
                GetPartitionIndexes484Example:
                  summary: Default GetPartitionIndexes 484 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetPartitionIndexesRequest'
      parameters:
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetPartitionIndexes
      summary: Amazon Glue Get Partition Indexes
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.GetPartitionIndexes API'
components:
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    Token:
      type: string
    KeySchemaElementList:
      type: array
      items:
        $ref: '#/components/schemas/KeySchemaElement'
      minItems: 1
    BackfillErrors:
      type: array
      items:
        $ref: '#/components/schemas/BackfillError'
    PartitionValueList:
      type: object
      required:
      - Values
      properties:
        Values:
          allOf:
          - $ref: '#/components/schemas/ValueStringList'
          - description: The list of values.
      description: Contains a list of values defining partitions.
    KeySchemaElement:
      type: object
      required:
      - Name
      - Type
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of a partition key.
        Type:
          allOf:
          - $ref: '#/components/schemas/ColumnTypeString'
          - description: The type of a partition key.
      description: A partition key pair consisting of a name and a type.
    EntityNotFoundException: {}
    CatalogIdString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    PartitionIndexStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - FAILED
    PartitionIndexDescriptorList:
      type: array
      items:
        $ref: '#/components/schemas/PartitionIndexDescriptor'
    BackfillErroredPartitionsList:
      type: array
      items:
        $ref: '#/components/schemas/PartitionValueList'
    PartitionIndexDescriptor:
      type: object
      required:
      - IndexName
      - Keys
      - IndexStatus
      properties:
        IndexName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the partition index.
        Keys:
          allOf:
          - $ref: '#/components/schemas/KeySchemaElementList'
          - description: A list of one or more keys, as <code>KeySchemaElement</code> structures, for the partition index.
        IndexStatus:
          allOf:
          - $ref: '#/components/schemas/PartitionIndexStatus'
          - description: '<p>The status of the partition index. </p> <p>The possible statuses are:</p> <ul> <li> <p>CREATING: The index is being created. When an index is in a CREATING state, the index or its table cannot be deleted.</p> </li> <li> <p>ACTIVE: The index creation succeeds.</p> </li> <li> <p>FAILED: The index creation fails. </p> </li> <li> <p>DELETING: The index is deleted from the list of indexes.</p> </li> </ul>'
        BackfillErrors:
          allOf:
          - $ref: '#/components/schemas/BackfillErrors'
          - description: A list of errors that can occur when registering partition indexes for an existing table.
      description: A descriptor for a partition index in a table.
    InternalServiceException: {}
    BackfillError:
      type: object
      properties:
        Code:
          allOf:
          - $ref: '#/components/schemas/BackfillErrorCode'
          - description: The error code for an error that occurred when registering partition indexes for an existing table.
        Partitions:
          allOf:
          - $ref: '#/components/schemas/BackfillErroredPartitionsList'
          - description: A list of a limited number of partitions in the response.
      description: '<p>A list of errors that can occur when registering partition indexes for an existing table.</p> <p>These errors give the details about why an index registration failed and provide a limited number of partitions in the response, so that you can fix the partitions at fault and try registering the index again. The most common set of errors that can occur are categorized as follows:</p> <ul> <li> <p>EncryptedPartitionError: The partitions are encrypted.</p> </li> <li> <p>InvalidPartitionTypeDataError: The partition value doesn''t match the data type for that partition column.</p> </li> <li> <p>MissingPartitionValueError: The partitions are encrypted.</p> </li> <li> <p>UnsupportedPartitionCharacterError: Characters inside the partition value are not supported. For example: U+0000 , U+0001, U+0002.</p> </li> <li> <p>InternalError: Any error which does not belong to other error codes.</p> </li> </ul>'
    ColumnTypeString:
      type: string
      minLength: 0
      maxLength: 131072
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    InvalidInputException: {}
    GetPartitionIndexesRequest:
      type: object
      required:
      - DatabaseName
      - TableName
      title: GetPartitionIndexesRequest
      properties:
        CatalogId:
          allOf:
          - $ref: '#/components/schemas/CatalogIdString'
          - description: The catalog ID where the table resides.
        DatabaseName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: Specifies the name of a database from which you want to retrieve partition indexes.
        TableName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: Specifies the name of a table for which you want to retrieve the partition indexes.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/Token'
          - description: A continuation token, included if this is a continuation call.
    ValueString:
      type: string
      maxLength: 1024
    BackfillErrorCode:
      type: string
      enum:
      - ENCRYPTED_PARTITION_ERROR
      - INTERNAL_ERROR
      - INVALID_PARTITION_TYPE_DATA_ERROR
      - MISSING_PARTITION_VALUE_ERROR
      - UNSUPPORTED_PARTITION_CHARACTER_ERROR
    ConflictException: {}
    OperationTimeoutException: {}
    ValueStringList:
      type: array
      items:
        $ref: '#/components/schemas/ValueString'
    GetPartitionIndexesResponse:
      type: object
      properties:
        PartitionIndexDescriptorList:
          allOf:
          - $ref: '#/components/schemas/PartitionIndexDescriptorList'
          - description: A list of index descriptors.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/Token'
          - description: A continuation token, present if the current list segment is not the last.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
