openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetCrawlerMetrics API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.GetCrawlerMetrics API'
paths:
  /#X-Amz-Target=AWSGlue.GetCrawlerMetrics:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetCrawlerMetrics
      description: Retrieves metrics about specified crawlers.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCrawlerMetricsResponse'
              examples:
                GetCrawlerMetrics200Example:
                  summary: Default GetCrawlerMetrics 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                GetCrawlerMetrics480Example:
                  summary: Default GetCrawlerMetrics 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCrawlerMetricsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetCrawlerMetrics
      summary: Amazon Glue Get Crawler Metrics
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.GetCrawlerMetrics API'
components:
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  schemas:
    OperationTimeoutException: {}
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    Token:
      type: string
    Boolean:
      type: boolean
    NonNegativeInteger:
      type: integer
      minimum: 0
    NonNegativeDouble:
      type: number
      format: double
      minimum: 0
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    CrawlerMetrics:
      type: object
      properties:
        CrawlerName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the crawler.
        TimeLeftSeconds:
          allOf:
          - $ref: '#/components/schemas/NonNegativeDouble'
          - description: The estimated time left to complete a running crawl.
        StillEstimating:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: True if the crawler is still estimating how long it will take to complete this run.
        LastRuntimeSeconds:
          allOf:
          - $ref: '#/components/schemas/NonNegativeDouble'
          - description: The duration of the crawler's most recent run, in seconds.
        MedianRuntimeSeconds:
          allOf:
          - $ref: '#/components/schemas/NonNegativeDouble'
          - description: The median duration of this crawler's runs, in seconds.
        TablesCreated:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInteger'
          - description: The number of tables created by this crawler.
        TablesUpdated:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInteger'
          - description: The number of tables updated by this crawler.
        TablesDeleted:
          allOf:
          - $ref: '#/components/schemas/NonNegativeInteger'
          - description: The number of tables deleted by this crawler.
      description: Metrics for a specified crawler.
    CrawlerNameList:
      type: array
      items:
        $ref: '#/components/schemas/NameString'
      minItems: 0
      maxItems: 100
    CrawlerMetricsList:
      type: array
      items:
        $ref: '#/components/schemas/CrawlerMetrics'
    GetCrawlerMetricsResponse:
      type: object
      properties:
        CrawlerMetricsList:
          allOf:
          - $ref: '#/components/schemas/CrawlerMetricsList'
          - description: A list of metrics for the specified crawler.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/Token'
          - description: A continuation token, if the returned list does not contain the last metric available.
    GetCrawlerMetricsRequest:
      type: object
      title: GetCrawlerMetricsRequest
      properties:
        CrawlerNameList:
          allOf:
          - $ref: '#/components/schemas/CrawlerNameList'
          - description: A list of the names of crawlers about which to retrieve metrics.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: The maximum size of a list to return.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/Token'
          - description: A continuation token, if this is a continuation call.
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
