openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetCustomEntityType API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.GetCustomEntityType API'
paths:
  /#X-Amz-Target=AWSGlue.GetCustomEntityType:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetCustomEntityType
      description: Retrieves the details of a custom pattern by specifying its name.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCustomEntityTypeResponse'
              examples:
                GetCustomEntityType200Example:
                  summary: Default GetCustomEntityType 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                GetCustomEntityType480Example:
                  summary: Default GetCustomEntityType 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                GetCustomEntityType481Example:
                  summary: Default GetCustomEntityType 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                GetCustomEntityType482Example:
                  summary: Default GetCustomEntityType 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                GetCustomEntityType483Example:
                  summary: Default GetCustomEntityType 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '484':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                GetCustomEntityType484Example:
                  summary: Default GetCustomEntityType 484 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetCustomEntityTypeRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetCustomEntityType
      summary: Amazon Glue Get Custom Entity Type
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.GetCustomEntityType API'
components:
  schemas:
    InvalidInputException: {}
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    EntityNotFoundException: {}
    AccessDeniedException: {}
    InternalServiceException: {}
    GetCustomEntityTypeResponse:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the custom pattern that you retrieved.
        RegexString:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: A regular expression string that is used for detecting sensitive data in a custom pattern.
        ContextWords:
          allOf:
          - $ref: '#/components/schemas/ContextWords'
          - description: A list of context words if specified when you created the custom pattern. If none of these context words are found within the vicinity of the regular expression the data will not be detected as sensitive data.
    GetCustomEntityTypeRequest:
      type: object
      required:
      - Name
      title: GetCustomEntityTypeRequest
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the custom pattern that you want to retrieve.
    ContextWords:
      type: array
      items:
        $ref: '#/components/schemas/NameString'
      minItems: 1
      maxItems: 20
    OperationTimeoutException: {}
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
