openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.UpdateSchema API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.UpdateSchema API'
paths:
  /#X-Amz-Target=AWSGlue.UpdateSchema:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: UpdateSchema
      description: 'Updates the description, compatibility setting, or version checkpoint for a schema set.


        For updating the compatibility setting, the call will not validate compatibility for the entire set of schema versions with the new compatibility setting. If the value for Compatibility is provided, the VersionNumber (a checkpoint) is also required. The API will validate the checkpoint version number for consistency.


        If the value for the VersionNumber (checkpoint) is provided, Compatibility is optional and this can be used to set/reset a checkpoint for the schema.


        This update will happen only if the schema is in the AVAILABLE state.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSchemaResponse'
              examples:
                UpdateSchema200Example:
                  summary: Default UpdateSchema 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                UpdateSchema480Example:
                  summary: Default UpdateSchema 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                UpdateSchema481Example:
                  summary: Default UpdateSchema 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                UpdateSchema482Example:
                  summary: Default UpdateSchema 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: ConcurrentModificationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConcurrentModificationException'
              examples:
                UpdateSchema483Example:
                  summary: Default UpdateSchema 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '484':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                UpdateSchema484Example:
                  summary: Default UpdateSchema 484 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSchemaInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.UpdateSchema
      summary: Amazon Glue Update Schema
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.UpdateSchema API'
components:
  schemas:
    DescriptionString:
      type: string
      minLength: 0
      maxLength: 2048
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    AccessDeniedException: {}
    ConcurrentModificationException: {}
    InvalidInputException: {}
    InternalServiceException: {}
    SchemaId:
      type: object
      properties:
        SchemaArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: The Amazon Resource Name (ARN) of the schema. One of <code>SchemaArn</code> or <code>SchemaName</code> has to be provided.
        SchemaName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema. One of <code>SchemaArn</code> or <code>SchemaName</code> has to be provided.
        RegistryName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema registry that contains the schema.
      description: The unique ID of the schema in the Glue schema registry.
    UpdateSchemaInput:
      type: object
      required:
      - SchemaId
      title: UpdateSchemaInput
      properties:
        SchemaId:
          allOf:
          - $ref: '#/components/schemas/SchemaId'
          - description: '<p>This is a wrapper structure to contain schema identity fields. The structure contains:</p> <ul> <li> <p>SchemaId$SchemaArn: The Amazon Resource Name (ARN) of the schema. One of <code>SchemaArn</code> or <code>SchemaName</code> has to be provided.</p> </li> <li> <p>SchemaId$SchemaName: The name of the schema. One of <code>SchemaArn</code> or <code>SchemaName</code> has to be provided.</p> </li> </ul>'
        SchemaVersionNumber:
          allOf:
          - $ref: '#/components/schemas/SchemaVersionNumber'
          - description: Version number required for check pointing. One of <code>VersionNumber</code> or <code>Compatibility</code> has to be provided.
        Compatibility:
          allOf:
          - $ref: '#/components/schemas/Compatibility'
          - description: The new compatibility setting for the schema.
        Description:
          allOf:
          - $ref: '#/components/schemas/DescriptionString'
          - description: The new description for the schema.
    SchemaRegistryNameString:
      type: string
      pattern: '[a-zA-Z0-9-_$#.]+'
      minLength: 1
      maxLength: 255
    VersionLongNumber:
      type: integer
      minimum: 1
      maximum: 100000
    EntityNotFoundException: {}
    GlueResourceArn:
      type: string
      pattern: arn:(aws|aws-us-gov|aws-cn):glue:.*
      minLength: 1
      maxLength: 10240
    Compatibility:
      type: string
      enum:
      - NONE
      - DISABLED
      - BACKWARD
      - BACKWARD_ALL
      - FORWARD
      - FORWARD_ALL
      - FULL
      - FULL_ALL
    UpdateSchemaResponse:
      type: object
      properties:
        SchemaArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: The Amazon Resource Name (ARN) of the schema.
        SchemaName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema.
        RegistryName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the registry that contains the schema.
    LatestSchemaVersionBoolean:
      type: boolean
    SchemaVersionNumber:
      type: object
      properties:
        LatestVersion:
          allOf:
          - $ref: '#/components/schemas/LatestSchemaVersionBoolean'
          - description: The latest version available for the schema.
        VersionNumber:
          allOf:
          - $ref: '#/components/schemas/VersionLongNumber'
          - description: The version number of the schema.
      description: A structure containing the schema version information.
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
