openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.ListSchemas API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.ListSchemas API'
paths:
  /#X-Amz-Target=AWSGlue.ListSchemas:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListSchemas
      description: 'Returns a list of schemas with minimal details. Schemas in Deleting status will not be included in the results. Empty results will be returned if there are no schemas available.


        When the RegistryId is not provided, all the schemas across registries will be part of the API response.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSchemasResponse'
              examples:
                ListSchemas200Example:
                  summary: Default ListSchemas 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                ListSchemas480Example:
                  summary: Default ListSchemas 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListSchemas481Example:
                  summary: Default ListSchemas 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                ListSchemas482Example:
                  summary: Default ListSchemas 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                ListSchemas483Example:
                  summary: Default ListSchemas 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListSchemasInput'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.ListSchemas
      summary: Amazon Glue List Schemas
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.ListSchemas API'
components:
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    SchemaListDefinition:
      type: array
      items:
        $ref: '#/components/schemas/SchemaListItem'
    EntityNotFoundException: {}
    ListSchemasInput:
      type: object
      title: ListSchemasInput
      properties:
        RegistryId:
          allOf:
          - $ref: '#/components/schemas/RegistryId'
          - description: A wrapper structure that may contain the registry name and Amazon Resource Name (ARN).
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/MaxResultsNumber'
          - description: Maximum number of results required per page. If the value is not supplied, this will be defaulted to 25 per page.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryTokenString'
          - description: A continuation token, if this is a continuation call.
    CreatedTimestamp:
      type: string
    UpdatedTimestamp:
      type: string
    SchemaListItem:
      type: object
      properties:
        RegistryName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: the name of the registry where the schema resides.
        SchemaName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema.
        SchemaArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: The Amazon Resource Name (ARN) for the schema.
        Description:
          allOf:
          - $ref: '#/components/schemas/DescriptionString'
          - description: A description for the schema.
        SchemaStatus:
          allOf:
          - $ref: '#/components/schemas/SchemaStatus'
          - description: The status of the schema.
        CreatedTime:
          allOf:
          - $ref: '#/components/schemas/CreatedTimestamp'
          - description: The date and time that a schema was created.
        UpdatedTime:
          allOf:
          - $ref: '#/components/schemas/UpdatedTimestamp'
          - description: The date and time that a schema was updated.
      description: An object that contains minimal details for a schema.
    SchemaRegistryNameString:
      type: string
      pattern: '[a-zA-Z0-9-_$#.]+'
      minLength: 1
      maxLength: 255
    ListSchemasResponse:
      type: object
      properties:
        Schemas:
          allOf:
          - $ref: '#/components/schemas/SchemaListDefinition'
          - description: An array of <code>SchemaListItem</code> objects containing details of each schema.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryTokenString'
          - description: A continuation token for paginating the returned list of tokens, returned if the current segment of the list is not the last.
    AccessDeniedException: {}
    InternalServiceException: {}
    SchemaStatus:
      type: string
      enum:
      - AVAILABLE
      - PENDING
      - DELETING
    GlueResourceArn:
      type: string
      pattern: arn:(aws|aws-us-gov|aws-cn):glue:.*
      minLength: 1
      maxLength: 10240
    InvalidInputException: {}
    DescriptionString:
      type: string
      minLength: 0
      maxLength: 2048
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    MaxResultsNumber:
      type: integer
      minimum: 1
      maximum: 100
    SchemaRegistryTokenString:
      type: string
    RegistryId:
      type: object
      properties:
        RegistryName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: 'Name of the registry. Used only for lookup. One of <code>RegistryArn</code> or <code>RegistryName</code> has to be provided. '
        RegistryArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: Arn of the registry to be updated. One of <code>RegistryArn</code> or <code>RegistryName</code> has to be provided.
      description: A wrapper structure that may contain the registry name and Amazon Resource Name (ARN).
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
