openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.ListMLTransforms API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: 'AWS Glue #X Amz Target=AWSGlue.ListMLTransforms API'
paths:
  /#X-Amz-Target=AWSGlue.ListMLTransforms:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListMLTransforms
      description: Retrieves a sortable, filterable list of existing Glue machine learning transforms in this Amazon Web Services account, or the resources with the specified tag. This operation takes the optional Tags field, which you can use as a filter of the responses so that tagged resources can be retrieved as a group. If you choose to use tag filtering, only resources with the tags are retrieved.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListMLTransformsResponse'
              examples:
                ListMLTransforms200Example:
                  summary: Default ListMLTransforms 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                ListMLTransforms480Example:
                  summary: Default ListMLTransforms 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                ListMLTransforms481Example:
                  summary: Default ListMLTransforms 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                ListMLTransforms482Example:
                  summary: Default ListMLTransforms 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                ListMLTransforms483Example:
                  summary: Default ListMLTransforms 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListMLTransformsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.ListMLTransforms
      summary: Amazon Glue List M L Transforms
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - 'AWS Glue #X Amz Target=AWSGlue.ListMLTransforms API'
components:
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
  schemas:
    TransformSchema:
      type: array
      items:
        $ref: '#/components/schemas/SchemaColumn'
      maxItems: 100
    TagsMap:
      type: object
      minProperties: 0
      maxProperties: 50
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    TransformSortColumnType:
      type: string
      enum:
      - NAME
      - TRANSFORM_TYPE
      - STATUS
      - CREATED
      - LAST_MODIFIED
    ListMLTransformsResponse:
      type: object
      required:
      - TransformIds
      properties:
        TransformIds:
          allOf:
          - $ref: '#/components/schemas/TransformIdList'
          - description: The identifiers of all the machine learning transforms in the account, or the machine learning transforms with the specified tags.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: A continuation token, if the returned list does not contain the last metric available.
    GlueVersionString:
      type: string
      pattern: ^\w+\.\w+$
      minLength: 1
      maxLength: 255
    SortDirectionType:
      type: string
      enum:
      - DESCENDING
      - ASCENDING
    TransformSortCriteria:
      type: object
      required:
      - Column
      - SortDirection
      properties:
        Column:
          allOf:
          - $ref: '#/components/schemas/TransformSortColumnType'
          - description: The column to be used in the sorting criteria that are associated with the machine learning transform.
        SortDirection:
          allOf:
          - $ref: '#/components/schemas/SortDirectionType'
          - description: The sort direction to be used in the sorting criteria that are associated with the machine learning transform.
      description: The sorting criteria that are associated with the machine learning transform.
    EntityNotFoundException: {}
    TransformStatusType:
      type: string
      enum:
      - NOT_READY
      - READY
      - DELETING
    ColumnNameString:
      type: string
      minLength: 1
      maxLength: 1024
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    SchemaColumn:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/ColumnNameString'
          - description: The name of the column.
        DataType:
          allOf:
          - $ref: '#/components/schemas/ColumnTypeString'
          - description: The type of data in the column.
      description: A key-value pair representing a column and data type that this transform can run against. The <code>Schema</code> parameter of the <code>MLTransform</code> may contain up to 100 of these structures.
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    TransformFilterCriteria:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: A unique transform name that is used to filter the machine learning transforms.
        TransformType:
          allOf:
          - $ref: '#/components/schemas/TransformType'
          - description: The type of machine learning transform that is used to filter the machine learning transforms.
        Status:
          allOf:
          - $ref: '#/components/schemas/TransformStatusType'
          - description: Filters the list of machine learning transforms by the last known status of the transforms (to indicate whether a transform can be used or not). One of "NOT_READY", "READY", or "DELETING".
        GlueVersion:
          allOf:
          - $ref: '#/components/schemas/GlueVersionString'
          - description: This value determines which version of Glue this machine learning transform is compatible with. Glue 1.0 is recommended for most customers. If the value is not set, the Glue compatibility defaults to Glue 0.9. For more information, see <a href="https://docs.aws.amazon.com/glue/latest/dg/release-notes.html#release-notes-versions">Glue Versions</a> in the developer guide.
        CreatedBefore:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time and date before which the transforms were created.
        CreatedAfter:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The time and date after which the transforms were created.
        LastModifiedBefore:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Filter on transforms last modified before this date.
        LastModifiedAfter:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Filter on transforms last modified after this date.
        Schema:
          allOf:
          - $ref: '#/components/schemas/TransformSchema'
          - description: Filters on datasets with a specific schema. The <code>Map&lt;Column, Type&gt;</code> object is an array of key-value pairs representing the schema this transform accepts, where <code>Column</code> is the name of a column, and <code>Type</code> is the type of the data such as an integer or string. Has an upper bound of 100 columns.
      description: The criteria used to filter the machine learning transforms.
    ListMLTransformsRequest:
      type: object
      title: ListMLTransformsRequest
      properties:
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: A continuation token, if this is a continuation request.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: The maximum size of a list to return.
        Filter:
          allOf:
          - $ref: '#/components/schemas/TransformFilterCriteria'
          - description: A <code>TransformFilterCriteria</code> used to filter the machine learning transforms.
        Sort:
          allOf:
          - $ref: '#/components/schemas/TransformSortCriteria'
          - description: A <code>TransformSortCriteria</code> used to sort the machine learning transforms.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagsMap'
          - description: Specifies to return only these tagged resources.
    TransformIdList:
      type: array
      items:
        $ref: '#/components/schemas/HashString'
    PaginationToken:
      type: string
    InternalServiceException: {}
    ColumnTypeString:
      type: string
      minLength: 0
      maxLength: 131072
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    HashString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    InvalidInputException: {}
    TransformType:
      type: string
      enum:
      - FIND_MATCHES
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    Timestamp:
      type: string
      format: date-time
    OperationTimeoutException: {}
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
