# x-archived-from: amazon-glue-x-amz-target-awsglue-checkschemaversionvalidity-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.CheckSchemaVersionValidity…'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.CheckSchemaVersionValidity'
paths:
  /#X-Amz-Target=AWSGlue.CheckSchemaVersionValidity:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CheckSchemaVersionValidity
      description: Validates the supplied schema. This call has no side effects, it simply validates using the supplied schema using DataFormat as the format. Since it does not take a schema set name, no compatibility checks are performed.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckSchemaVersionValidityResponse'
              examples:
                CheckSchemaVersionValidity200Example:
                  summary: Default CheckSchemaVersionValidity 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                CheckSchemaVersionValidity480Example:
                  summary: Default CheckSchemaVersionValidity 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                CheckSchemaVersionValidity481Example:
                  summary: Default CheckSchemaVersionValidity 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                CheckSchemaVersionValidity482Example:
                  summary: Default CheckSchemaVersionValidity 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckSchemaVersionValidityInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.CheckSchemaVersionValidity
      summary: Amazon Glue Check Schema Version Validity
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.CheckSchemaVersionValidity'
components:
  schemas:
    InternalServiceException: {}
    SchemaValidationError:
      type: string
      minLength: 1
      maxLength: 5000
    CheckSchemaVersionValidityInput:
      type: object
      required:
      - DataFormat
      - SchemaDefinition
      title: CheckSchemaVersionValidityInput
      properties:
        DataFormat:
          allOf:
          - $ref: '#/components/schemas/DataFormat'
          - description: The data format of the schema definition. Currently <code>AVRO</code>, <code>JSON</code> and <code>PROTOBUF</code> are supported.
        SchemaDefinition:
          allOf:
          - $ref: '#/components/schemas/SchemaDefinitionString'
          - description: The definition of the schema that has to be validated.
    IsVersionValid:
      type: boolean
    SchemaDefinitionString:
      type: string
      pattern: .*\S.*
      minLength: 1
      maxLength: 170000
    DataFormat:
      type: string
      enum:
      - AVRO
      - JSON
      - PROTOBUF
    AccessDeniedException: {}
    InvalidInputException: {}
    CheckSchemaVersionValidityResponse:
      type: object
      properties:
        Valid:
          allOf:
          - $ref: '#/components/schemas/IsVersionValid'
          - description: Return true, if the schema is valid and false otherwise.
        Error:
          allOf:
          - $ref: '#/components/schemas/SchemaValidationError'
          - description: A validation failure error message.
  parameters:
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
