# x-archived-from: amazon-glue-x-amz-target-awsglue-createuserdefinedfunction-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.CreateUserDefinedFunction API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.CreateUserDefinedFunction'
paths:
  /#X-Amz-Target=AWSGlue.CreateUserDefinedFunction:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateUserDefinedFunction
      description: Creates a new function definition in the Data Catalog.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserDefinedFunctionResponse'
              examples:
                CreateUserDefinedFunction200Example:
                  summary: Default CreateUserDefinedFunction 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: AlreadyExistsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlreadyExistsException'
              examples:
                CreateUserDefinedFunction480Example:
                  summary: Default CreateUserDefinedFunction 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                CreateUserDefinedFunction481Example:
                  summary: Default CreateUserDefinedFunction 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                CreateUserDefinedFunction482Example:
                  summary: Default CreateUserDefinedFunction 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                CreateUserDefinedFunction483Example:
                  summary: Default CreateUserDefinedFunction 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '484':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                CreateUserDefinedFunction484Example:
                  summary: Default CreateUserDefinedFunction 484 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '485':
          description: ResourceNumberLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNumberLimitExceededException'
              examples:
                CreateUserDefinedFunction485Example:
                  summary: Default CreateUserDefinedFunction 485 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '486':
          description: GlueEncryptionException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GlueEncryptionException'
              examples:
                CreateUserDefinedFunction486Example:
                  summary: Default CreateUserDefinedFunction 486 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDefinedFunctionRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.CreateUserDefinedFunction
      summary: Amazon Glue Create User Defined Function
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.CreateUserDefinedFunction'
components:
  schemas:
    ResourceUri:
      type: object
      properties:
        ResourceType:
          allOf:
          - $ref: '#/components/schemas/ResourceType'
          - description: The type of the resource.
        Uri:
          allOf:
          - $ref: '#/components/schemas/URI'
          - description: The URI for accessing the resource.
      description: The URIs for function resources.
    AlreadyExistsException: {}
    ResourceNumberLimitExceededException: {}
    PrincipalType:
      type: string
      enum:
      - USER
      - ROLE
      - GROUP
    UserDefinedFunctionInput:
      type: object
      properties:
        FunctionName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the function.
        ClassName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The Java class that contains the function code.
        OwnerName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The owner of the function.
        OwnerType:
          allOf:
          - $ref: '#/components/schemas/PrincipalType'
          - description: The owner type.
        ResourceUris:
          allOf:
          - $ref: '#/components/schemas/ResourceUriList'
          - description: The resource URIs for the function.
      description: A structure used to create or update a user-defined function.
    InvalidInputException: {}
    GlueEncryptionException: {}
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    ResourceUriList:
      type: array
      items:
        $ref: '#/components/schemas/ResourceUri'
      minItems: 0
      maxItems: 1000
    CreateUserDefinedFunctionRequest:
      type: object
      required:
      - DatabaseName
      - FunctionInput
      title: CreateUserDefinedFunctionRequest
      properties:
        CatalogId:
          allOf:
          - $ref: '#/components/schemas/CatalogIdString'
          - description: The ID of the Data Catalog in which to create the function. If none is provided, the Amazon Web Services account ID is used by default.
        DatabaseName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the catalog database in which to create the function.
        FunctionInput:
          allOf:
          - $ref: '#/components/schemas/UserDefinedFunctionInput'
          - description: A <code>FunctionInput</code> object that defines the function to create in the Data Catalog.
    EntityNotFoundException: {}
    InternalServiceException: {}
    URI:
      type: string
      minLength: 1
      maxLength: 1024
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    OperationTimeoutException: {}
    CreateUserDefinedFunctionResponse:
      type: object
      properties: {}
    ResourceType:
      type: string
      enum:
      - JAR
      - FILE
      - ARCHIVE
    CatalogIdString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
