# x-archived-from: amazon-glue-x-amz-target-awsglue-getmltaskruns-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetMLTaskRuns API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.GetMLTaskRuns'
paths:
  /#X-Amz-Target=AWSGlue.GetMLTaskRuns:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetMLTaskRuns
      description: 'Gets a list of runs for a machine learning transform. Machine learning task runs are asynchronous tasks that Glue runs on your behalf as part of various machine learning workflows. You can get a sortable, filterable list of machine learning task runs by calling GetMLTaskRuns with their parent transform''s TransformID and other optional parameters as documented in this section.


        This operation returns a list of historic runs and must be paginated.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMLTaskRunsResponse'
              examples:
                GetMLTaskRuns200Example:
                  summary: Default GetMLTaskRuns 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                GetMLTaskRuns480Example:
                  summary: Default GetMLTaskRuns 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                GetMLTaskRuns481Example:
                  summary: Default GetMLTaskRuns 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                GetMLTaskRuns482Example:
                  summary: Default GetMLTaskRuns 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                GetMLTaskRuns483Example:
                  summary: Default GetMLTaskRuns 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetMLTaskRunsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetMLTaskRuns
      summary: Amazon Glue Get M L Task Runs
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.GetMLTaskRuns'
components:
  schemas:
    HashString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    InvalidInputException: {}
    TaskRunList:
      type: array
      items:
        $ref: '#/components/schemas/TaskRun'
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    ImportLabelsTaskRunProperties:
      type: object
      properties:
        InputS3Path:
          allOf:
          - $ref: '#/components/schemas/UriString'
          - description: The Amazon Simple Storage Service (Amazon S3) path from where you will import the labels.
        Replace:
          allOf:
          - $ref: '#/components/schemas/ReplaceBoolean'
          - description: Indicates whether to overwrite your existing labels.
      description: Specifies configuration properties for an importing labels task run.
    TaskRunFilterCriteria:
      type: object
      properties:
        TaskRunType:
          allOf:
          - $ref: '#/components/schemas/TaskType'
          - description: The type of task run.
        Status:
          allOf:
          - $ref: '#/components/schemas/TaskStatusType'
          - description: The current status of the task run.
        StartedBefore:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Filter on task runs started before this date.
        StartedAfter:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: Filter on task runs started after this date.
      description: The criteria that are used to filter the task runs for the machine learning transform.
    TaskRunProperties:
      type: object
      properties:
        TaskType:
          allOf:
          - $ref: '#/components/schemas/TaskType'
          - description: The type of task run.
        ImportLabelsTaskRunProperties:
          allOf:
          - $ref: '#/components/schemas/ImportLabelsTaskRunProperties'
          - description: The configuration properties for an importing labels task run.
        ExportLabelsTaskRunProperties:
          allOf:
          - $ref: '#/components/schemas/ExportLabelsTaskRunProperties'
          - description: The configuration properties for an exporting labels task run.
        LabelingSetGenerationTaskRunProperties:
          allOf:
          - $ref: '#/components/schemas/LabelingSetGenerationTaskRunProperties'
          - description: The configuration properties for a labeling set generation task run.
        FindMatchesTaskRunProperties:
          allOf:
          - $ref: '#/components/schemas/FindMatchesTaskRunProperties'
          - description: The configuration properties for a find matches task run.
      description: The configuration properties for the task run.
    PaginationToken:
      type: string
    GetMLTaskRunsResponse:
      type: object
      properties:
        TaskRuns:
          allOf:
          - $ref: '#/components/schemas/TaskRunList'
          - description: A list of task runs that are associated with the transform.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: A pagination token, if more results are available.
    TaskRunSortColumnType:
      type: string
      enum:
      - TASK_RUN_TYPE
      - STATUS
      - STARTED
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    TaskType:
      type: string
      enum:
      - EVALUATION
      - LABELING_SET_GENERATION
      - IMPORT_LABELS
      - EXPORT_LABELS
      - FIND_MATCHES
    SortDirectionType:
      type: string
      enum:
      - DESCENDING
      - ASCENDING
    EntityNotFoundException: {}
    LabelingSetGenerationTaskRunProperties:
      type: object
      properties:
        OutputS3Path:
          allOf:
          - $ref: '#/components/schemas/UriString'
          - description: The Amazon Simple Storage Service (Amazon S3) path where you will generate the labeling set.
      description: Specifies configuration properties for a labeling set generation task run.
    InternalServiceException: {}
    FindMatchesTaskRunProperties:
      type: object
      properties:
        JobId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The job ID for the Find Matches task run.
        JobName:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name assigned to the job for the Find Matches task run.
        JobRunId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The job run ID for the Find Matches task run.
      description: Specifies configuration properties for a Find Matches task run.
    GetMLTaskRunsRequest:
      type: object
      required:
      - TransformId
      title: GetMLTaskRunsRequest
      properties:
        TransformId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The unique identifier of the machine learning transform.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/PaginationToken'
          - description: A token for pagination of the results. The default is empty.
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: 'The maximum number of results to return. '
        Filter:
          allOf:
          - $ref: '#/components/schemas/TaskRunFilterCriteria'
          - description: The filter criteria, in the <code>TaskRunFilterCriteria</code> structure, for the task run.
        Sort:
          allOf:
          - $ref: '#/components/schemas/TaskRunSortCriteria'
          - description: The sorting criteria, in the <code>TaskRunSortCriteria</code> structure, for the task run.
    OperationTimeoutException: {}
    ReplaceBoolean:
      type: boolean
    UriString:
      type: string
    GenericString:
      type: string
    TaskRun:
      type: object
      properties:
        TransformId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The unique identifier for the transform.
        TaskRunId:
          allOf:
          - $ref: '#/components/schemas/HashString'
          - description: The unique identifier for this task run.
        Status:
          allOf:
          - $ref: '#/components/schemas/TaskStatusType'
          - description: The current status of the requested task run.
        LogGroupName:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The names of the log group for secure logging, associated with this task run.
        Properties:
          allOf:
          - $ref: '#/components/schemas/TaskRunProperties'
          - description: Specifies configuration properties associated with this task run.
        ErrorString:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The list of error strings associated with this task run.
        StartedOn:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date and time that this task run started.
        LastModifiedOn:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The last point in time that the requested task run was updated.
        CompletedOn:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The last point in time that the requested task run was completed.
        ExecutionTime:
          allOf:
          - $ref: '#/components/schemas/ExecutionTime'
          - description: The amount of time (in seconds) that the task run consumed resources.
      description: The sampling parameters that are associated with the machine learning transform.
    ExportLabelsTaskRunProperties:
      type: object
      properties:
        OutputS3Path:
          allOf:
          - $ref: '#/components/schemas/UriString'
          - description: The Amazon Simple Storage Service (Amazon S3) path where you will export the labels.
      description: Specifies configuration properties for an exporting labels task run.
    TaskStatusType:
      type: string
      enum:
      - STARTING
      - RUNNING
      - STOPPING
      - STOPPED
      - SUCCEEDED
      - FAILED
      - TIMEOUT
    TaskRunSortCriteria:
      type: object
      required:
      - Column
      - SortDirection
      properties:
        Column:
          allOf:
          - $ref: '#/components/schemas/TaskRunSortColumnType'
          - description: The column to be used to sort the list of task runs for the machine learning transform.
        SortDirection:
          allOf:
          - $ref: '#/components/schemas/SortDirectionType'
          - description: The sort direction to be used to sort the list of task runs for the machine learning transform.
      description: The sorting criteria that are used to sort the list of task runs for the machine learning transform.
    ExecutionTime:
      type: integer
    Timestamp:
      type: string
      format: date-time
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
