# x-archived-from: amazon-glue-x-amz-target-awsglue-getschema-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetSchema API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.GetSchema'
paths:
  /#X-Amz-Target=AWSGlue.GetSchema:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetSchema
      description: Describes the specified schema in detail.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSchemaResponse'
              examples:
                GetSchema200Example:
                  summary: Default GetSchema 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                GetSchema480Example:
                  summary: Default GetSchema 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                GetSchema481Example:
                  summary: Default GetSchema 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                GetSchema482Example:
                  summary: Default GetSchema 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                GetSchema483Example:
                  summary: Default GetSchema 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetSchemaInput'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetSchema
      summary: Amazon Glue Get Schema
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.GetSchema'
components:
  schemas:
    DataFormat:
      type: string
      enum:
      - AVRO
      - JSON
      - PROTOBUF
    VersionLongNumber:
      type: integer
      minimum: 1
      maximum: 100000
    InvalidInputException: {}
    SchemaId:
      type: object
      properties:
        SchemaArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: The Amazon Resource Name (ARN) of the schema. One of <code>SchemaArn</code> or <code>SchemaName</code> has to be provided.
        SchemaName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema. One of <code>SchemaArn</code> or <code>SchemaName</code> has to be provided.
        RegistryName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema registry that contains the schema.
      description: The unique ID of the schema in the Glue schema registry.
    SchemaCheckpointNumber:
      type: integer
      minimum: 1
      maximum: 100000
    GlueResourceArn:
      type: string
      pattern: arn:(aws|aws-us-gov|aws-cn):glue:.*
      minLength: 1
      maxLength: 10240
    EntityNotFoundException: {}
    SchemaRegistryNameString:
      type: string
      pattern: '[a-zA-Z0-9-_$#.]+'
      minLength: 1
      maxLength: 255
    InternalServiceException: {}
    SchemaStatus:
      type: string
      enum:
      - AVAILABLE
      - PENDING
      - DELETING
    UpdatedTimestamp:
      type: string
    GetSchemaInput:
      type: object
      required:
      - SchemaId
      title: GetSchemaInput
      properties:
        SchemaId:
          allOf:
          - $ref: '#/components/schemas/SchemaId'
          - description: '<p>This is a wrapper structure to contain schema identity fields. The structure contains:</p> <ul> <li> <p>SchemaId$SchemaArn: The Amazon Resource Name (ARN) of the schema. Either <code>SchemaArn</code> or <code>SchemaName</code> and <code>RegistryName</code> has to be provided.</p> </li> <li> <p>SchemaId$SchemaName: The name of the schema. Either <code>SchemaArn</code> or <code>SchemaName</code> and <code>RegistryName</code> has to be provided.</p> </li> </ul>'
    CreatedTimestamp:
      type: string
    GetSchemaResponse:
      type: object
      properties:
        RegistryName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the registry.
        RegistryArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: The Amazon Resource Name (ARN) of the registry.
        SchemaName:
          allOf:
          - $ref: '#/components/schemas/SchemaRegistryNameString'
          - description: The name of the schema.
        SchemaArn:
          allOf:
          - $ref: '#/components/schemas/GlueResourceArn'
          - description: The Amazon Resource Name (ARN) of the schema.
        Description:
          allOf:
          - $ref: '#/components/schemas/DescriptionString'
          - description: A description of schema if specified when created
        DataFormat:
          allOf:
          - $ref: '#/components/schemas/DataFormat'
          - description: The data format of the schema definition. Currently <code>AVRO</code>, <code>JSON</code> and <code>PROTOBUF</code> are supported.
        Compatibility:
          allOf:
          - $ref: '#/components/schemas/Compatibility'
          - description: The compatibility mode of the schema.
        SchemaCheckpoint:
          allOf:
          - $ref: '#/components/schemas/SchemaCheckpointNumber'
          - description: The version number of the checkpoint (the last time the compatibility mode was changed).
        LatestSchemaVersion:
          allOf:
          - $ref: '#/components/schemas/VersionLongNumber'
          - description: The latest version of the schema associated with the returned schema definition.
        NextSchemaVersion:
          allOf:
          - $ref: '#/components/schemas/VersionLongNumber'
          - description: The next version of the schema associated with the returned schema definition.
        SchemaStatus:
          allOf:
          - $ref: '#/components/schemas/SchemaStatus'
          - description: The status of the schema.
        CreatedTime:
          allOf:
          - $ref: '#/components/schemas/CreatedTimestamp'
          - description: The date and time the schema was created.
        UpdatedTime:
          allOf:
          - $ref: '#/components/schemas/UpdatedTimestamp'
          - description: The date and time the schema was updated.
    AccessDeniedException: {}
    DescriptionString:
      type: string
      minLength: 0
      maxLength: 2048
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    Compatibility:
      type: string
      enum:
      - NONE
      - DISABLED
      - BACKWARD
      - BACKWARD_ALL
      - FORWARD
      - FORWARD_ALL
      - FULL
      - FULL_ALL
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
