# x-archived-from: amazon-glue-x-amz-target-awsglue-listsessions-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.ListSessions API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.ListSessions'
paths:
  /#X-Amz-Target=AWSGlue.ListSessions:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: ListSessions
      description: Retrieve a list of sessions.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListSessionsResponse'
              examples:
                ListSessions200Example:
                  summary: Default ListSessions 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
              examples:
                ListSessions480Example:
                  summary: Default ListSessions 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                ListSessions481Example:
                  summary: Default ListSessions 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                ListSessions482Example:
                  summary: Default ListSessions 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                ListSessions483Example:
                  summary: Default ListSessions 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListSessionsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.ListSessions
      summary: Amazon Glue List Sessions
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.ListSessions'
components:
  schemas:
    SessionIdList:
      type: array
      items:
        $ref: '#/components/schemas/NameString'
    SessionCommand:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: Specifies the name of the SessionCommand. Can be 'glueetl' or 'gluestreaming'.
        PythonVersion:
          allOf:
          - $ref: '#/components/schemas/PythonVersionString'
          - description: Specifies the Python version. The Python version indicates the version supported for jobs of type Spark.
      description: The <code>SessionCommand</code> that runs the job.
    OrchestrationToken:
      type: string
      maxLength: 400000
    TagValue:
      type: string
      minLength: 0
      maxLength: 256
    InvalidInputException: {}
    TimestampValue:
      type: string
      format: date-time
    OrchestrationArgumentsValue:
      type: string
      minLength: 0
      maxLength: 4096
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    SessionList:
      type: array
      items:
        $ref: '#/components/schemas/Session'
    PythonVersionString:
      type: string
      pattern: ^([2-3]|3[.]9)$
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    Session:
      type: object
      properties:
        Id:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The ID of the session.
        CreatedOn:
          allOf:
          - $ref: '#/components/schemas/TimestampValue'
          - description: The time and date when the session was created.
        Status:
          allOf:
          - $ref: '#/components/schemas/SessionStatus'
          - description: 'The session status. '
        ErrorMessage:
          allOf:
          - $ref: '#/components/schemas/DescriptionString'
          - description: The error message displayed during the session.
        Description:
          allOf:
          - $ref: '#/components/schemas/DescriptionString'
          - description: The description of the session.
        Role:
          allOf:
          - $ref: '#/components/schemas/OrchestrationRoleArn'
          - description: The name or Amazon Resource Name (ARN) of the IAM role associated with the Session.
        Command:
          allOf:
          - $ref: '#/components/schemas/SessionCommand'
          - description: The command object.See SessionCommand.
        DefaultArguments:
          allOf:
          - $ref: '#/components/schemas/OrchestrationArgumentsMap'
          - description: 'A map array of key-value pairs. Max is 75 pairs. '
        Connections:
          allOf:
          - $ref: '#/components/schemas/ConnectionsList'
          - description: The number of connections used for the session.
        Progress:
          allOf:
          - $ref: '#/components/schemas/DoubleValue'
          - description: The code execution progress of the session.
        MaxCapacity:
          allOf:
          - $ref: '#/components/schemas/NullableDouble'
          - description: 'The number of Glue data processing units (DPUs) that can be allocated when the job runs. A DPU is a relative measure of processing power that consists of 4 vCPUs of compute capacity and 16 GB memory. '
        SecurityConfiguration:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the SecurityConfiguration structure to be used with the session.
        GlueVersion:
          allOf:
          - $ref: '#/components/schemas/GlueVersionString'
          - description: The Glue version determines the versions of Apache Spark and Python that Glue supports. The GlueVersion must be greater than 2.0.
      description: The period in which a remote Spark runtime environment is running.
    OrchestrationArgumentsMap:
      type: object
      minProperties: 0
      maxProperties: 75
      additionalProperties:
        $ref: '#/components/schemas/OrchestrationArgumentsValue'
    InternalServiceException: {}
    OrchestrationStringList:
      type: array
      items:
        $ref: '#/components/schemas/GenericString'
    OperationTimeoutException: {}
    GlueVersionString:
      type: string
      pattern: ^\w+\.\w+$
      minLength: 1
      maxLength: 255
    OrchestrationRoleArn:
      type: string
      pattern: arn:aws[^:]*:iam::[0-9]*:role/.+
      minLength: 20
      maxLength: 2048
    OrchestrationNameString:
      type: string
      pattern: '[\.\-_A-Za-z0-9]+'
      minLength: 1
      maxLength: 128
    ListSessionsResponse:
      type: object
      properties:
        Ids:
          allOf:
          - $ref: '#/components/schemas/SessionIdList'
          - description: 'Returns the ID of the session. '
        Sessions:
          allOf:
          - $ref: '#/components/schemas/SessionList'
          - description: 'Returns the session object. '
        NextToken:
          allOf:
          - $ref: '#/components/schemas/OrchestrationToken'
          - description: 'The token for the next set of results, or null if there are no more result. '
    GenericString:
      type: string
    ConnectionsList:
      type: object
      properties:
        Connections:
          allOf:
          - $ref: '#/components/schemas/OrchestrationStringList'
          - description: A list of connections used by the job.
      description: Specifies the connections used by a job.
    TagsMap:
      type: object
      minProperties: 0
      maxProperties: 50
      additionalProperties:
        $ref: '#/components/schemas/TagValue'
    SessionStatus:
      type: string
      enum:
      - PROVISIONING
      - READY
      - FAILED
      - TIMEOUT
      - STOPPING
      - STOPPED
    AccessDeniedException: {}
    DescriptionString:
      type: string
      minLength: 0
      maxLength: 2048
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*'
    NullableDouble:
      type: number
      format: double
    DoubleValue:
      type: number
      format: double
    ListSessionsRequest:
      type: object
      title: ListSessionsRequest
      properties:
        NextToken:
          allOf:
          - $ref: '#/components/schemas/OrchestrationToken'
          - description: 'The token for the next set of results, or null if there are no more result. '
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: 'The maximum number of results. '
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagsMap'
          - description: 'Tags belonging to the session. '
        RequestOrigin:
          allOf:
          - $ref: '#/components/schemas/OrchestrationNameString'
          - description: 'The origin of the request. '
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
