# x-archived-from: amazon-glue-x-amz-target-awsglue-getdevendpoints-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.GetDevEndpoints API'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.GetDevEndpoints'
paths:
  /#X-Amz-Target=AWSGlue.GetDevEndpoints:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: GetDevEndpoints
      description: 'Retrieves all the development endpoints in this Amazon Web Services account.


        When you create a development endpoint in a virtual private cloud (VPC), Glue returns only a private IP address and the public IP address field is not populated. When you create a non-VPC development endpoint, Glue returns only a public IP address.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDevEndpointsResponse'
              examples:
                GetDevEndpoints200Example:
                  summary: Default GetDevEndpoints 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: EntityNotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EntityNotFoundException'
              examples:
                GetDevEndpoints480Example:
                  summary: Default GetDevEndpoints 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                GetDevEndpoints481Example:
                  summary: Default GetDevEndpoints 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                GetDevEndpoints482Example:
                  summary: Default GetDevEndpoints 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                GetDevEndpoints483Example:
                  summary: Default GetDevEndpoints 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetDevEndpointsRequest'
      parameters:
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.GetDevEndpoints
      summary: Amazon Glue Get Dev Endpoints
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.GetDevEndpoints'
components:
  schemas:
    DevEndpoint:
      type: object
      properties:
        EndpointName:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The name of the <code>DevEndpoint</code>.
        RoleArn:
          allOf:
          - $ref: '#/components/schemas/RoleArn'
          - description: The Amazon Resource Name (ARN) of the IAM role used in this <code>DevEndpoint</code>.
        SecurityGroupIds:
          allOf:
          - $ref: '#/components/schemas/StringList'
          - description: A list of security group identifiers used in this <code>DevEndpoint</code>.
        SubnetId:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The subnet ID for this <code>DevEndpoint</code>.
        YarnEndpointAddress:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The YARN endpoint address used by this <code>DevEndpoint</code>.
        PrivateAddress:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: A private IP address to access the <code>DevEndpoint</code> within a VPC if the <code>DevEndpoint</code> is created within one. The <code>PrivateAddress</code> field is present only when you create the <code>DevEndpoint</code> within your VPC.
        ZeppelinRemoteSparkInterpreterPort:
          allOf:
          - $ref: '#/components/schemas/IntegerValue'
          - description: The Apache Zeppelin port for the remote Apache Spark interpreter.
        PublicAddress:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The public IP address used by this <code>DevEndpoint</code>. The <code>PublicAddress</code> field is present only when you create a non-virtual private cloud (VPC) <code>DevEndpoint</code>.
        Status:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The current status of this <code>DevEndpoint</code>.
        WorkerType:
          allOf:
          - $ref: '#/components/schemas/WorkerType'
          - description: '<p>The type of predefined worker that is allocated to the development endpoint. Accepts a value of Standard, G.1X, or G.2X.</p> <ul> <li> <p>For the <code>Standard</code> worker type, each worker provides 4 vCPU, 16 GB of memory and a 50GB disk, and 2 executors per worker.</p> </li> <li> <p>For the <code>G.1X</code> worker type, each worker maps to 1 DPU (4 vCPU, 16 GB of memory, 64 GB disk), and provides 1 executor per worker. We recommend this worker type for memory-intensive jobs.</p> </li> <li> <p>For the <code>G.2X</code> worker type, each worker maps to 2 DPU (8 vCPU, 32 GB of memory, 128 GB disk), and provides 1 executor per worker. We recommend this worker type for memory-intensive jobs.</p> </li> </ul> <p>Known issue: when a development endpoint is created with the <code>G.2X</code> <code>WorkerType</code> configuration, the Spark drivers for the development endpoint will run on 4 vCPU, 16 GB of memory, and a 64 GB disk. </p>'
        GlueVersion:
          allOf:
          - $ref: '#/components/schemas/GlueVersionString'
          - description: <p>Glue version determines the versions of Apache Spark and Python that Glue supports. The Python version indicates the version supported for running your ETL scripts on development endpoints. </p> <p>For more information about the available Glue versions and corresponding Spark and Python versions, see <a href="https://docs.aws.amazon.com/glue/latest/dg/add-job.html">Glue version</a> in the developer guide.</p> <p>Development endpoints that are created without specifying a Glue version default to Glue 0.9.</p> <p>You can specify a version of Python support for development endpoints by using the <code>Arguments</code> parameter in the <code>CreateDevEndpoint</code> or <code>UpdateDevEndpoint</code> APIs. If no arguments are provided, the version defaults to Python 2.</p>
        NumberOfWorkers:
          allOf:
          - $ref: '#/components/schemas/NullableInteger'
          - description: <p>The number of workers of a defined <code>workerType</code> that are allocated to the development endpoint.</p> <p>The maximum number of workers you can define are 299 for <code>G.1X</code>, and 149 for <code>G.2X</code>. </p>
        NumberOfNodes:
          allOf:
          - $ref: '#/components/schemas/IntegerValue'
          - description: The number of Glue Data Processing Units (DPUs) allocated to this <code>DevEndpoint</code>.
        AvailabilityZone:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The Amazon Web Services Availability Zone where this <code>DevEndpoint</code> is located.
        VpcId:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The ID of the virtual private cloud (VPC) used by this <code>DevEndpoint</code>.
        ExtraPythonLibsS3Path:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: <p>The paths to one or more Python libraries in an Amazon S3 bucket that should be loaded in your <code>DevEndpoint</code>. Multiple values must be complete paths separated by a comma.</p> <note> <p>You can only use pure Python libraries with a <code>DevEndpoint</code>. Libraries that rely on C extensions, such as the <a href="http://pandas.pydata.org/">pandas</a> Python data analysis library, are not currently supported.</p> </note>
        ExtraJarsS3Path:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: <p>The path to one or more Java <code>.jar</code> files in an S3 bucket that should be loaded in your <code>DevEndpoint</code>.</p> <note> <p>You can only use pure Java/Scala libraries with a <code>DevEndpoint</code>.</p> </note>
        FailureReason:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The reason for a current failure in this <code>DevEndpoint</code>.
        LastUpdateStatus:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The status of the last update.
        CreatedTimestamp:
          allOf:
          - $ref: '#/components/schemas/TimestampValue'
          - description: The point in time at which this DevEndpoint was created.
        LastModifiedTimestamp:
          allOf:
          - $ref: '#/components/schemas/TimestampValue'
          - description: The point in time at which this <code>DevEndpoint</code> was last modified.
        PublicKey:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: The public key to be used by this <code>DevEndpoint</code> for authentication. This attribute is provided for backward compatibility because the recommended attribute to use is public keys.
        PublicKeys:
          allOf:
          - $ref: '#/components/schemas/PublicKeysList'
          - description: <p>A list of public keys to be used by the <code>DevEndpoints</code> for authentication. Using this attribute is preferred over a single public key because the public keys allow you to have a different private key per client.</p> <note> <p>If you previously created an endpoint with a public key, you must remove that key to be able to set a list of public keys. Call the <code>UpdateDevEndpoint</code> API operation with the public key content in the <code>deletePublicKeys</code> attribute, and the list of new keys in the <code>addPublicKeys</code> attribute.</p> </note>
        SecurityConfiguration:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name of the <code>SecurityConfiguration</code> structure to be used with this <code>DevEndpoint</code>.
        Arguments:
          allOf:
          - $ref: '#/components/schemas/MapValue'
          - description: '<p>A map of arguments used to configure the <code>DevEndpoint</code>.</p> <p>Valid arguments are:</p> <ul> <li> <p> <code>"--enable-glue-datacatalog": ""</code> </p> </li> </ul> <p>You can specify a version of Python support for development endpoints by using the <code>Arguments</code> parameter in the <code>CreateDevEndpoint</code> or <code>UpdateDevEndpoint</code> APIs. If no arguments are provided, the version defaults to Python 2.</p>'
      description: A development endpoint where a developer can remotely debug extract, transform, and load (ETL) scripts.
    TimestampValue:
      type: string
      format: date-time
    InvalidInputException: {}
    MapValue:
      type: object
      minProperties: 0
      maxProperties: 100
      additionalProperties:
        $ref: '#/components/schemas/GenericString'
    PageSize:
      type: integer
      minimum: 1
      maximum: 1000
    WorkerType:
      type: string
      enum:
      - Standard
      - G.1X
      - G.2X
      - G.025X
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    EntityNotFoundException: {}
    NullableInteger:
      type: integer
    InternalServiceException: {}
    IntegerValue:
      type: integer
    RoleArn:
      type: string
      pattern: arn:aws:iam::\d{12}:role/.*
    GlueVersionString:
      type: string
      pattern: ^\w+\.\w+$
      minLength: 1
      maxLength: 255
    OperationTimeoutException: {}
    PublicKeysList:
      type: array
      items:
        $ref: '#/components/schemas/GenericString'
      maxItems: 5
    GetDevEndpointsRequest:
      type: object
      title: GetDevEndpointsRequest
      properties:
        MaxResults:
          allOf:
          - $ref: '#/components/schemas/PageSize'
          - description: The maximum size of information to return.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: A continuation token, if this is a continuation call.
    GenericString:
      type: string
    DevEndpointList:
      type: array
      items:
        $ref: '#/components/schemas/DevEndpoint'
    StringList:
      type: array
      items:
        $ref: '#/components/schemas/GenericString'
    GetDevEndpointsResponse:
      type: object
      properties:
        DevEndpoints:
          allOf:
          - $ref: '#/components/schemas/DevEndpointList'
          - description: A list of <code>DevEndpoint</code> definitions.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/GenericString'
          - description: A continuation token, if not all <code>DevEndpoint</code> definitions have yet been returned.
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
