# x-archived-from: amazon-glue-x-amz-target-awsglue-createsecurityconfiguration-api-openapi.yml
# x-archived-on: 2026-09-26
openapi: 3.2.0
info:
  version: '2017-03-31'
  x-release: v4
  title: 'AWS Glue #X Amz Target=AWSGlue.CreateSecurityConfiguration…'
  description: 'Glue

    Defines the public endpoint for the Glue service.'
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: glue
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/glue-2017-03-31.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: https://glue.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS Glue multi-region endpoint
- url: http://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
- url: https://glue.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS Glue endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=AWSGlue.CreateSecurityConfiguration'
paths:
  /#X-Amz-Target=AWSGlue.CreateSecurityConfiguration:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateSecurityConfiguration
      description: Creates a new security configuration. A security configuration is a set of security properties that can be used by Glue. You can use a security configuration to encrypt data at rest. For information about using security configurations in Glue, see Encrypting Data Written by Crawlers, Jobs, and Development Endpoints.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSecurityConfigurationResponse'
              examples:
                CreateSecurityConfiguration200Example:
                  summary: Default CreateSecurityConfiguration 200 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '480':
          description: AlreadyExistsException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlreadyExistsException'
              examples:
                CreateSecurityConfiguration480Example:
                  summary: Default CreateSecurityConfiguration 480 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '481':
          description: InvalidInputException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidInputException'
              examples:
                CreateSecurityConfiguration481Example:
                  summary: Default CreateSecurityConfiguration 481 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '482':
          description: InternalServiceException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServiceException'
              examples:
                CreateSecurityConfiguration482Example:
                  summary: Default CreateSecurityConfiguration 482 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '483':
          description: OperationTimeoutException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationTimeoutException'
              examples:
                CreateSecurityConfiguration483Example:
                  summary: Default CreateSecurityConfiguration 483 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
        '484':
          description: ResourceNumberLimitExceededException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNumberLimitExceededException'
              examples:
                CreateSecurityConfiguration484Example:
                  summary: Default CreateSecurityConfiguration 484 response
                  x-microcks-default: true
                  value:
                    JobRunId: jr_abc123
                    State: SUCCEEDED
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSecurityConfigurationRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - AWSGlue.CreateSecurityConfiguration
      summary: Amazon Glue Create Security Configuration
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=AWSGlue.CreateSecurityConfiguration'
components:
  schemas:
    AlreadyExistsException: {}
    ResourceNumberLimitExceededException: {}
    S3EncryptionMode:
      type: string
      enum:
      - DISABLED
      - SSE-KMS
      - SSE-S3
    TimestampValue:
      type: string
      format: date-time
    InvalidInputException: {}
    CreateSecurityConfigurationResponse:
      type: object
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name assigned to the new security configuration.
        CreatedTimestamp:
          allOf:
          - $ref: '#/components/schemas/TimestampValue'
          - description: The time at which the new security configuration was created.
    EncryptionConfiguration:
      type: object
      properties:
        S3Encryption:
          allOf:
          - $ref: '#/components/schemas/S3EncryptionList'
          - description: The encryption configuration for Amazon Simple Storage Service (Amazon S3) data.
        CloudWatchEncryption:
          allOf:
          - $ref: '#/components/schemas/CloudWatchEncryption'
          - description: The encryption configuration for Amazon CloudWatch.
        JobBookmarksEncryption:
          allOf:
          - $ref: '#/components/schemas/JobBookmarksEncryption'
          - description: The encryption configuration for job bookmarks.
      description: Specifies an encryption configuration.
    CloudWatchEncryption:
      type: object
      properties:
        CloudWatchEncryptionMode:
          allOf:
          - $ref: '#/components/schemas/CloudWatchEncryptionMode'
          - description: The encryption mode to use for CloudWatch data.
        KmsKeyArn:
          allOf:
          - $ref: '#/components/schemas/KmsKeyArn'
          - description: The Amazon Resource Name (ARN) of the KMS key to be used to encrypt the data.
      description: Specifies how Amazon CloudWatch data should be encrypted.
    S3Encryption:
      type: object
      properties:
        S3EncryptionMode:
          allOf:
          - $ref: '#/components/schemas/S3EncryptionMode'
          - description: The encryption mode to use for Amazon S3 data.
        KmsKeyArn:
          allOf:
          - $ref: '#/components/schemas/KmsKeyArn'
          - description: The Amazon Resource Name (ARN) of the KMS key to be used to encrypt the data.
      description: Specifies how Amazon Simple Storage Service (Amazon S3) data should be encrypted.
    NameString:
      type: string
      minLength: 1
      maxLength: 255
      x-pattern: '[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*'
    CloudWatchEncryptionMode:
      type: string
      enum:
      - DISABLED
      - SSE-KMS
    S3EncryptionList:
      type: array
      items:
        $ref: '#/components/schemas/S3Encryption'
    InternalServiceException: {}
    JobBookmarksEncryptionMode:
      type: string
      enum:
      - DISABLED
      - CSE-KMS
    OperationTimeoutException: {}
    CreateSecurityConfigurationRequest:
      type: object
      required:
      - Name
      - EncryptionConfiguration
      title: CreateSecurityConfigurationRequest
      properties:
        Name:
          allOf:
          - $ref: '#/components/schemas/NameString'
          - description: The name for the new security configuration.
        EncryptionConfiguration:
          allOf:
          - $ref: '#/components/schemas/EncryptionConfiguration'
          - description: The encryption configuration for the new security configuration.
    JobBookmarksEncryption:
      type: object
      properties:
        JobBookmarksEncryptionMode:
          allOf:
          - $ref: '#/components/schemas/JobBookmarksEncryptionMode'
          - description: The encryption mode to use for job bookmarks data.
        KmsKeyArn:
          allOf:
          - $ref: '#/components/schemas/KmsKeyArn'
          - description: The Amazon Resource Name (ARN) of the KMS key to be used to encrypt the data.
      description: Specifies how job bookmark data should be encrypted.
    KmsKeyArn:
      type: string
      pattern: arn:aws:kms:.*
  parameters:
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/glue/
x-hasEquivalentPaths: true
